### PR TITLE
refactor: merge yosymfony/resource-watcher

### PR DESCRIPTION
**Pull request by pierresh**
Include `yosymfony/resource-watcher` directly in PHPUnit watcher so that it is easier to manage dependencies.

### CODE REVIEW

**Comment by freekmurze** [comment]
It seems like some of the tests are failing. Could you take a look?

Feel free to drop support for older versions of PHP.

**Comment by pierresh** [comment]
Unit tests were ok (including those of Yosymfony) but indeed there was a conflict among dependencies for PHP 8.1. I adjusted and now it should be ok.

Now:
- Minimum PHP version 8.1
- Require Symfony 6 or 7

**Comment by freekmurze** [comment]
Only the lower deps fail now, could you take a look?

**Comment by pierresh** [comment]
Sorry, but I do not know how to fix these problems.

**P8.2 - prefer-lowest - ubuntu-latest**
**P8.1 - prefer-lowest - ubuntu-latest**
```bash
There was 1 PHPUnit warning:

1) Test results may not be as expected because the XML configuration file did not pass validation:

  Line 9:
  - Element 'source': This element is not expected.
```
However, tests run fine on my computer with PHPUnit 10.5.20 and PHPUnit 11.1.3.

I do not understand why it complains about phpunit.xml


**P8 - prefer-lowest - ubuntu-latest**, that is because I set 8.1 as the minimum PHP version while the test environment has PHP 8.0.
```bash
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^8.1 but your php version (8.0.30) does not satisfy that requirement.
  Problem 2
    - phpunit/phpunit[[10](https://github.com/spatie/phpunit-watcher/actions/runs/9184477117/job/25265699033?pr=161#step:4:11).0.0, ..., 10.5.20] require php >=8.1 -> your php version (8.0.30) does not satisfy that requirement.
    - phpunit/phpunit[[11](https://github.com/spatie/phpunit-watcher/actions/runs/9184477117/job/25265699033?pr=161#step:4:12).0.0, ..., 11.1.3] require php >=8.2 -> your php version (8.0.30) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^10.0 | ^11.0 -> satisfiable by phpunit/phpunit[10.0.0, ..., 10.5.20, 11.0.0, ..., 11.1.3].
```

**Comment by freekmurze** [comment]
I'll take care of those failing tests myself. Thanks for your work on this

**Comment by KentarouTakeda** [comment]
Thanks so much!

This pull request allows us to use this package with Laravel. It seems that there are many people who have been waiting for it. Great job!

**Pull request merged**
