### PR TITLE
[WIP] fix compatibility with yosymfony/resource-watcher

### PR DESCRIPTION
**Pull request by romainnorberg**
cf: https://github.com/spatie/phpunit-watcher/pull/99

### Todo
- [ ] add tests on `Watcher->startWatching()`

### CODE REVIEW

**Comment by robguy21** [comment]
Hey, need any help on this?

Really keen to get this fix in

**Comment by romainnorberg** [comment]
hello @robguy21 I think the fix could be merged. @spatie I'm sorry I did not test enough

**Comment by robguy21** [comment]
@romainnorberg think you just need to adjust the order of your `use` statements-

```
use Clue\React\Stdio\Stdio;
 use React\EventLoop\Factory;
 use React\Stream\ThroughStream;
-use Symfony\Component\Finder\Finder;
 use Spatie\PhpUnitWatcher\Screens\Phpunit;
+use Symfony\Component\Finder\Finder;
 use Yosymfony\ResourceWatcher\Crc32ContentHash;
-use Yosymfony\ResourceWatcher\ResourceWatcher;
 use Yosymfony\ResourceWatcher\ResourceCacheMemory;
+use Yosymfony\ResourceWatcher\ResourceWatcher;
```

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
