### PR TITLE
Merge command line PHPUnit arguments with config arguments

### LINKED ISSUE #129: PHPUnit arguments from config are wiped out when changing group
### Reproduction Steps

1. Add PHPUnit arguments to `phpunit-watcher.yml.dist`:
    ```yml
     phpunit:
      arguments: -d xdebug.mode=off --process-isolation
     ```
    
1. Start `phpunit-watcher`, and see the expected output:
     > Starting PHPUnit with arguments: `-d xdebug.mode=off --process-isolation`

1. Use the menu to change the `group` (or `filter`, `file`, etc)
1. See that `phpunit-watcher.yml.dist` arguments are no longer used:
    > Starting PHPUnit with arguments: `--group=patterns`

In one of my codebases, that makes `phpunit-watcher` unusable, because the config arguments are required on every run (see #128).

### Potential Solution

On each run, the user-supplied arguments (`--group=patterns`) could be merged with the default arguments from `phpunit-watcher.yml`. User-supplied would override config arguments, but other config arguments would be preserved.

### Full output:

```
> composer run test:watch
> phpunit-watcher watch


PHPUnit Watcher
===============

 PHPUnit Watcher 1.12.1 by Spatie and contributors.

 Using options from configfile at `/public_html/phpunit-watcher.yml.dist`

 Tests will be rerun when *.php files are modified in
 * /public_html/./events/
 * /public_html/./patterns/


PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.14
Configuration: /public_html/phpunit.xml.dist

................................................................. 65 / 81 ( 80%)
...........I....                                                  81 / 81 (100%)

Time: 00:09.924, Memory: 10.00 MB

There was 1 incomplete test:

1) Dotorg\API\Events\Tests\Test_Events::test_port_remaining_tests
Not all of the tests from ./test-index.php have been ported to PHPUnit yet. See the notes in that file.

/public_html/events/1.0/tests/test-index-phpunit.php:1149

OK, but incomplete, skipped, or risky tests!
Tests: 81, Assertions: 111, Incomplete: 1.
Starting PHPUnit with arguments: `-d xdebug.mode=off --process-isolation`


Press a to run all tests.
Press t to filter by test name.
Press p to filter by file name.
Press g to filter by group name.
Press s to filter by test suite name.
Press r to run tests with a random seed.
Press q to quit the watcher.
Press Enter to trigger a test run.
g


Pattern mode usage
Type a pattern and press Enter to only run tests from a specific PHPUnit group.
Press Enter with an empty pattern to execute all tests in all files.

Start typing to filter by a test name.
pattern > patterns

PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.14
Configuration: /public_html/phpunit.xml.dist

....                                                                4 / 4 (100%)

Time: 00:00.387, Memory: 8.00 MB

OK (4 tests, 14 assertions)

Starting PHPUnit with arguments: `--group=patterns`
```

### PR DESCRIPTION
**Pull request by iandunn**
WIP

Fixes #129

### CODE REVIEW

**Comment by iandunn** [comment]
The first barrier I'm working on is how to parse the strings into associative arrays, so they can be merged.

`getopt()` would be nice, but it doesn't accept an arbitrary string; it doesn't seem like Symphony/Console does either. The internal logic of `getopt()` is too complex to easily simulate with `strtok`, `explode`, `preg_split`, etc.

Another option is just appending the CLI args to the config args. That's kind of ugly, because it can result in an arg string like `-d xdebug.mode=off --process-isolation --group=patterns --group=events`, but it'd be simple. I haven't tested enough cases to make sure there wouldn't be unintended consequences, though.

I'll keep looking for an elegant solution.

**Comment by iandunn** [comment]
A few libraries:

* https://github.com/docopt/docopt.php
* https://github.com/nategood/commando
* https://github.com/c9s/GetOptionKit

**Comment by iandunn** [comment]
It looks like PHPUnit's `Builder::fromParameters()` might be a good option, although it's internal and doesn't guarantee back-compat.

**Comment by iandunn** [comment]
@freekmurze , I've got a working solution to merge the config args with the runtime args, but I want make sure the general idea looks good to you before proceeding.

The libraries above aren't designed to accept arbitrary strings, and PHPUnit's internals turned out to be a dead end too. 

I found [a good custom solution on StackOverflow](https://stackoverflow.com/questions/65815738/merge-two-string-of-cli-options/65891967#65891967), and modified it to work in this context. The code is in `mergePHPUnitArguments()`.

It currently works with the initial startup, and the group screen. If you think that's good, I can clean it up, add tests, and implement it in the other screens.

**Comment by iandunn** [comment]
@freekmurze , I'm still interested in finishing this if you have any thoughts on the above comment.

**Comment by freekmurze** [comment]
I've decided not to take on the extra complexity for now.

**Pull request closed without merging**
